name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@2b3a426f9a2807e18eda89f9b9c15c8828ebaa4f # main

  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@2b3a426f9a2807e18eda89f9b9c15c8828ebaa4f # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@2b3a426f9a2807e18eda89f9b9c15c8828ebaa4f # main
