name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@cacb6a49ad62a7ef1b2d0338273d542a7bfca0c7 # main

  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@cacb6a49ad62a7ef1b2d0338273d542a7bfca0c7 # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@cacb6a49ad62a7ef1b2d0338273d542a7bfca0c7 # main
