name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    permissions:
      id-token: write
      contents: read
    uses: harryzcy/github-actions/.github/workflows/go.yml@fae1858434c87b9cf10fe8a78af1b57ebddd9666 # main
    with:
      latest: 1

  integration-test:
    name: Integration Tests
    needs: go-test
    strategy:
      matrix:
        go-version: ["1.27"]
        arch: ["amd64", "arm64"]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-26.04' || 'ubuntu-26.04-arm' }}
    permissions:
      id-token: write
    services:
      dynamodb:
        image: amazon/dynamodb-local@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4 # v2.2.0
        ports:
          - 8000:8000
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Run integration tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./integration/...
        env:
          DYNAMODB_TABLE: test
          DYNAMODB_ORIGINAL_INDEX: OriginalMessageIDIndex

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./coverage.txt
          use_oidc: true
